# Module: FsUtils.cmake
# Author: Peter Laptik
# Description: A set of helper functions for reading data (settings) from text files

# Reads variables from file (KEY=VALUE)
# FILE_PATH - file path (resolved against the current source dir)
function (read_variables_from_file FILE_PATH)
    set(ABS_FILE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/${FILE_PATH})
    if(NOT EXISTS ${ABS_FILE_PATH})
        message(FATAL_ERROR "Settings file is not found: ${ABS_FILE_PATH}")
    endif()
    file(STRINGS ${ABS_FILE_PATH} PROJECT_VARS)
    message(STATUS "Setting up project variables from the file: '${ABS_FILE_PATH}'")
        foreach(LINE ${PROJECT_VARS})
            string(REGEX MATCH "(.*)=(.*)" _ ${LINE})
            set(${CMAKE_MATCH_1} ${CMAKE_MATCH_2} PARENT_SCOPE)
            message(STATUS "\t ${CMAKE_MATCH_1} = ${CMAKE_MATCH_2}")
        endforeach()
endfunction()

# Reads list variables from file (KEY:=VALUE1 VALUE2 VALUE3 ...)
# FILE_PATH - file path
function (read_list_variables_from_file FILE_PATH)
    set(ABS_FILE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/${FILE_PATH})
    if(NOT EXISTS ${ABS_FILE_PATH})
        message(FATAL_ERROR "Settings file is not found: ${ABS_FILE_PATH}")
    endif()
    file(STRINGS ./${ABS_FILE_PATH} PROJECT_VARS)
    message(STATUS "Setting up project list variables from the file: '${FILE_PATH}'")
        foreach(LINE ${PROJECT_VARS})
            string(REGEX MATCH "(.*):=(.*)" _ ${LINE})
            string(REPLACE " " ";" STR_TO_LIST ${CMAKE_MATCH_2})
            separate_arguments(CMAKE_MATCH_2)
            set(${CMAKE_MATCH_1} ${CMAKE_MATCH_2} PARENT_SCOPE)
            message(STATUS "\t ${CMAKE_MATCH_1} = ${STR_TO_LIST}")
        endforeach()
endfunction()